### ISSUE TITLE
Example daemonset for ASP has the containers property incorrectly nested

### ISSUE THREAD

**Issue by andrewjjenkins** [F5Networks/f5-ci-docs#157]
## Version
v1

## Description
When using the example f5-asp-daemonset.yaml file, the DaemonSet will not start and Kubernetes will report an error:

    error: error validating "f5-asp-daemonset.yaml": error validating data: [field containers: is required, found invalid field template for v1.PodSpec]; if you choose to ignore these errors, turn validation off with --validate=false

The example template has containers as a child of template (spec -> template -> spec -> template -> containers), when it should be a child of spec directly (spec -> template -> spec -> containers).

Here is the example that produces the error:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: f5-asp
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: f5-asp
    spec:
      hostNetwork: true
      template:
        containers:
          - name: f5-asp
            image: "f5networks/asp:v1.0.0"
            args:
              # the config file is loaded from the ConfigMap; it contains the
              # ASP global config
              - --config-file
              - /etc/configmap/asp.config.json
            securityContext:
              privileged: false
            volumeMounts:
            # mount a new directory
            - name: plugin-config
              # the path the directory will be added to; do not change
              mountPath: /var/run/kubernetes/proxy-plugin
              readOnly: true
            # mount a new directory
            - name: asp-config
              # the path the directory will be added to; do not change
              mountPath: /etc/configmap
        volumes:
          - name: plugin-config
            hostPath:
              path: /var/run/kubernetes/proxy-plugin
          - name: asp-config
            # replace with name of your ASP ConfigMap
            configMap:
              name: f5-asp-config
```

Here is a fixed version that deploys:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: f5-asp
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: f5-asp
    spec:
      hostNetwork: true
      containers:
        - name: proxy-plugin
          image: f5networks/asp:v1.0.0
          args:
            - --config-file
            - /etc/configmap/asp.config.json
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /var/run/kubernetes/proxy-plugin
            name: plugin-config
            readOnly: true
          - mountPath: /etc/configmap
            name: asp-config
      volumes:
        - name: plugin-config
          hostPath:
            path: /var/run/kubernetes/proxy-plugin
        - name: asp-config
          configMap:
            name: f5-asp-config
```
